generation: 1
sets:
  - filters:
      - isMatch: true
        labels:
          - core
    dimensions:
      dds:
        - fastdds
        - cyclone
        - connext
      buildType:
        - debian
        - binary
        - source
      chip:
        - amd64
        - arm64
      os:
        - jammy
  - filters:
      - isMatch: true
        labels:
          - core
    dimensions:
      dds:
        - fastdds
        - cyclone
        - connext
      buildType:
        - debian
        - binary
        - source
      chip:
        - amd64
      os:
        - windows
  - filters:
      - isMatch: true
        labels:
          - core
    dimensions:
      dds:
        - fastdds
      buildType:
        - source
      chip:
        - amd64
      os:
        - focal
        - rhel 8
