generation: 1
sets:
  # Documentation
  - filters:
      - isMatch: true
        labels:
          - docs
      - isMatch: false
        labels:
          - launch-files
      - isMatch: false
        name: Launch system
        labels:
          - launch
    dimensions:
      dds:
        - fastdds

  # Features
  - filters:
      - isMatch: true
        labels:
          - feature
    dimensions:
      dds:
        - fastdds
      buildType:
        - debian
      os:
        - jammy

  # Core for Jammy
  - filters:
      - isMatch: true
        labels:
          - core
    dimensions:
      dds:
        - fastdds
        - cyclone
        - connext
      buildType:
        - debian
        - binary
        - source
      chip:
        - amd64
        - arm64
      os:
        - jammy

  # Core for Windows (no arm64)
  - filters:
      - isMatch: true
        labels:
          - core
    dimensions:
      dds:
        - fastdds
        - cyclone
        - connext
      buildType:
        - debian
        - binary
        - source
      chip:
        - amd64
      os:
        - windows
  # Core for tear 3 platforms
  - filters:
      - isMatch: true
        labels:
          - core
    dimensions:
      dds:
        - fastdds
      buildType:
        - source
      chip:
        - amd64
      os:
        - focal
        - rhel 8
